name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Py Test
      id: py-test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: ''
    - name: Custom
      id: custom
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Custom
        setup-command: pip install pytest
        command: pytest test.py
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PY-TEST_RESULTS: "${{steps.py-test.outputs.result}}"
        CUSTOM_RESULTS: "${{steps.custom.outputs.result}}"
      with:
        runners: py-test,custom
